CREATE DATABASE IF NOT EXISTS sample_api;
CREATE DATABASE IF NOT EXISTS nest_api;

CREATE USER IF NOT EXISTS 'heroes_app'@'%' IDENTIFIED BY 'heroes_app';
GRANT ALL PRIVILEGES ON *.* TO 'heroes_app'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
