// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleApi.Infrastructure.Data;

#nullable disable

namespace SampleApi.Infrastructure.Migrations
{
    [DbContext(typeof(SampleApiDbContext))]
    [Migration("20260504152004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.HeroEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("heroes", (string)null);
                });

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.HeroPowerEntity", b =>
                {
                    b.Property<string>("HeroId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PowerId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("HeroId", "PowerId");

                    b.HasIndex("PowerId");

                    b.HasIndex("HeroId", "Position");

                    b.ToTable("hero_powers", (string)null);
                });

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.PowerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("powers", (string)null);
                });

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.HeroPowerEntity", b =>
                {
                    b.HasOne("SampleApi.Infrastructure.Entities.HeroEntity", "Hero")
                        .WithMany("HeroPowers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleApi.Infrastructure.Entities.PowerEntity", "Power")
                        .WithMany("HeroPowers")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Power");
                });

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.HeroEntity", b =>
                {
                    b.Navigation("HeroPowers");
                });

            modelBuilder.Entity("SampleApi.Infrastructure.Entities.PowerEntity", b =>
                {
                    b.Navigation("HeroPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
